name: deep_learning_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - tensorflow=2.16.1
  - keras=3.3.3
  - numpy=1.26.4
  - pandas=2.2.1
  - matplotlib=3.8.4
  - seaborn=0.13.2
  - scikit-learn=1.4.2
  - pillow=10.3.0
  - protobuf=3.20.3
  - tqdm=4.66.4
  - pip:
      - h5py==3.11.0
      - opt-einsum==3.3.0
      - tensorboard==2.16.2
      - tensorflow-io-gcs-filesystem==0.37.0